#!/bin/sh
[ -f /etc/profile.d/RkEnv.sh ] && source /etc/profile.d/RkEnv.sh
case $1 in
	start)
		ulimit -c unlimited
        sh nice -19 /usr/bin/m8c&
		;;
	stop)
        killall m8c
		;;
	*)
		exit 1
		;;
esac
